config/routes.rb
Rails.application.routes.draw do
  resources :reviews, only: [:index]
  resources :movies, except: [:new, :edit] do
    resources :reviews, except: [:index]
  end
  get '/home', to: 'static_pages#home', as: 'home'
  get '/about', to: 'static_pages#about', as: 'about'

  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_movie
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.movie_id = @movie.id


    respond_to do |format|
      if @review.save
        format.html { redirect_to @movie, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else

        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_movie
      begin
        @movie = Movie.find(params[:movie_id])
      rescue
        @movie = nil
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:movie_id, :user_name, :user_email, :rating, :comment)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for([movie, review]) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>You are leaving a review for <%= movie.title %></div>

  <div class="field">
    <%= form.label :user_name %>
    <%= form.text_field :user_name %>
  </div>

  <div class="field">
    <%= form.label :user_email %>
    <%= form.text_field :user_email %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <div id="IconHolder"></div>
    <%= form.hidden_field :rating, id: "RatingInput" , value: 3 %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

<script> 

generateIcon()

function generateIcon () {
  let holder = document.getElementById("IconHolder")
  holder.innerHTML = `
    <div class="Icon">
      <%= image_tag ("score1.png"), alt: "1", id: "score1", class: "RatingIcon", onclick: "changeFaceStyle(this.id)" %>
    </div>
    <div class="Icon">
      <%= image_tag ("score2.png"), alt: "2", id: "score2", class: "RatingIcon", onclick: "changeFaceStyle(this.id)" %>
    </div>
    <div class="Icon">
      <%= image_tag ("score3.png"), alt: "3", id: "score3", class: "RatingIcon Selected", onclick: "changeFaceStyle(this.id)" %>
    </div>
    <div class="Icon">
      <%= image_tag ("score4.png"), alt: "4", id: "score4", class: "RatingIcon", onclick: "changeFaceStyle(this.id)" %>
    </div>
    <div class="Icon">
      <%= image_tag ("score5.png"), alt: "5", id: "score5", class: "RatingIcon", onclick: "changeFaceStyle(this.id)" %>
    </div>
  `
}

changeFaceStyle = (id) => {
  let face = document.getElementById(id);
  let rating_input = document.getElementById("RatingInput");
  rating_input.value = face.alt;
  for (let i = 1; i < 6; i++) {
    let cur_face = document.getElementById("score" + i );
    console.log(cur_face);
    if (cur_face == face) {
      cur_face.className = "RatingIcon Selected";
    } else {
      cur_face.className = "RatingIcon";
    }
  }
}

</script>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Movie</th>
      <th>User name</th>
      <th>User email</th>
      <th>Rating</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.movie_id %></td>
        <td><%= review.user_name %></td>
        <td><%= review.user_email %></td>
        <td><%= review.rating %></td>
        <td><%= review.comment %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', movie: @movie, review: @review %>

<%= link_to 'Back', movie_path(@movie) %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Movie:</strong>
  <%= @review.movie_id %>
</p>

<p>
  <strong>User name:</strong>
  <%= @review.user_name %>
</p>

<p>
  <strong>User email:</strong>
  <%= @review.user_email %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>